"""Schema for GUI-exposed settings.

Single source of truth: drives server-side validation (lib/settings.py)
and frontend form rendering (public/assets/js/settings.js).

Every key MUST exist in config.py with a matching type — enforced by
Test/test_settings_schema.py.

Entry fields:
  type       "int" | "float" | "bool" | "str" | "enum"
  min / max  required for int/float (inclusive bounds)
  choices    required for enum
  nullable   str only: empty input is stored as None
  max_length str only (default 100)
  secret     str only: UI renders a password input
  scope      "kiln" (lives in the active kiln settings profile) | "global"
  apply      "live" (setattr immediately)
             "next-firing" (setattr immediately; consumed at next run start)
             "restart" (persist only; effective after server restart)
  category   one of CATEGORY_ORDER
  label      short UI label
  help       one-line UI help text
  unit       optional; literal ("s", "%", "kW", ...) or the sentinels
             "temp" / "temp_per_hr" (rendered per the active temp_scale)
  safety     True -> IDLE-only guard, confirmation styling in UI
  mid_firing_editable  True -> editable while firing WITH explicit confirm
                       (only the ignore_* thermocouple-error flags)
  sim_only   True -> UI shows the setting only in simulation mode
"""

CATEGORY_ORDER = [
    "PID Tuning", "Kiln", "Firing Behavior", "Safety", "Cost",
    "Display", "Cooling", "MQTT", "Advanced", "Simulation",
]

SETTINGS_SCHEMA = {
    # ------------------------------------------------------ kiln scope
    "pid_kp": {"type": "float", "min": 0.0, "max": 10000.0, "scope": "kiln",
               "apply": "next-firing", "category": "PID Tuning",
               "label": "Proportional gain (Kp)",
               "help": "PID proportional term. Tune per kiln (see docs/pid_tuning.md)."},
    "pid_ki": {"type": "float", "min": 0.0, "max": 10000.0, "scope": "kiln",
               "apply": "next-firing", "category": "PID Tuning",
               "label": "Integral gain (Ki)",
               "help": "Inverted: a SMALLER number means MORE integral action."},
    "pid_kd": {"type": "float", "min": 0.0, "max": 10000.0, "scope": "kiln",
               "apply": "next-firing", "category": "PID Tuning",
               "label": "Derivative gain (Kd)",
               "help": "PID derivative term."},
    "pid_control_window": {"type": "int", "min": 1, "max": 500, "scope": "kiln",
                           "apply": "live", "category": "PID Tuning",
                           "label": "PID control window", "unit": "temp", "safety": True,
                           "help": "Outside this window the elements are forced 100% on/off and no integral accumulates."},
    "kw_elements": {"type": "float", "min": 0.1, "max": 100.0, "scope": "kiln",
                    "apply": "live", "category": "Kiln",
                    "label": "Element power", "unit": "kW",
                    "help": "Total element wattage when on; used for cost estimates. Reload the dashboard to see updated estimates."},
    "thermocouple_offset": {"type": "float", "min": -50.0, "max": 50.0, "scope": "kiln",
                            "apply": "restart", "category": "Kiln",
                            "label": "Thermocouple offset", "unit": "temp",
                            "help": "Added to every reading to correct a mis-calibrated thermocouple. Takes effect after restart."},
    "emergency_shutoff_temp": {"type": "int", "min": 100, "max": 2500, "scope": "kiln",
                               "apply": "live", "category": "Safety",
                               "label": "Emergency shutoff temperature", "unit": "temp", "safety": True,
                               "help": "The firing aborts at or above this temperature."},
    "kiln_must_catch_up": {"type": "bool", "scope": "kiln", "apply": "live",
                           "category": "Firing Behavior", "label": "Kiln must catch up",
                           "help": "Pause the schedule while the temperature is outside the PID window."},
    "throttle_below_temp": {"type": "int", "min": 0, "max": 2500, "scope": "kiln",
                            "apply": "live", "category": "Firing Behavior",
                            "label": "Throttle below", "unit": "temp",
                            "help": "Below this temperature, cap element output to the throttle percentage."},
    "throttle_percent": {"type": "int", "min": 1, "max": 100, "scope": "kiln",
                         "apply": "live", "category": "Firing Behavior",
                         "label": "Throttle percentage", "unit": "%",
                         "help": "Maximum element output while below the throttle temperature. 100 disables throttling."},
    "segment_complete_tolerance": {"type": "int", "min": 1, "max": 100, "scope": "kiln",
                                   "apply": "live", "category": "Firing Behavior",
                                   "label": "Segment complete tolerance", "unit": "temp",
                                   "help": "A segment advances when within this many degrees of its target."},
    "rate_deviation_warning": {"type": "int", "min": 1, "max": 1000, "scope": "kiln",
                               "apply": "live", "category": "Firing Behavior",
                               "label": "Rate deviation warning", "unit": "temp_per_hr",
                               "help": "Log a warning when the actual rate deviates from the target rate by more than this."},
    "estimated_max_heating_rate": {"type": "int", "min": 1, "max": 2000, "scope": "kiln",
                                   "apply": "live", "category": "Firing Behavior",
                                   "label": "Estimated max heating rate", "unit": "temp_per_hr",
                                   "help": "Used to estimate the duration of \"max\" rate segments."},
    "estimated_natural_cooling_rate": {"type": "int", "min": 1, "max": 2000, "scope": "kiln",
                                       "apply": "live", "category": "Firing Behavior",
                                       "label": "Estimated natural cooling rate", "unit": "temp_per_hr",
                                       "help": "Used to estimate the duration of \"cool\" rate segments."},
    "rate_lookahead_seconds": {"type": "int", "min": 0, "max": 600, "scope": "kiln",
                               "apply": "live", "category": "Firing Behavior",
                               "label": "Rate lookahead", "unit": "s",
                               "help": "How far the rate-based target leads the actual temperature."},
    "max_target_divergence": {"type": "int", "min": 1, "max": 500, "scope": "kiln",
                              "apply": "live", "category": "Firing Behavior",
                              "label": "Max target divergence", "unit": "temp",
                              "help": "Caps how far the target may lead the actual temperature."},
    "use_rate_based_control": {"type": "bool", "scope": "kiln", "apply": "next-firing",
                               "category": "Firing Behavior", "label": "Rate-based control",
                               "help": "Use v2 rate-based control; off = legacy time-based control."},

    # ---------------------------------------------------- global scope
    "seek_start": {"type": "bool", "scope": "global", "apply": "live",
                   "category": "Firing Behavior", "label": "Seek start",
                   "help": "If the kiln is already hot when a firing starts, skip ahead to the matching point in the schedule."},
    "kwh_rate": {"type": "float", "min": 0.0, "max": 10.0, "scope": "global",
                 "apply": "live", "category": "Cost",
                 "label": "Electricity rate", "unit": "/kWh",
                 "help": "Cost per kilowatt-hour. Reload the dashboard to see updated estimates."},
    "currency_type": {"type": "str", "max_length": 5, "scope": "global",
                      "apply": "live", "category": "Cost",
                      "label": "Currency symbol",
                      "help": "Shown next to cost estimates."},
    "temp_scale": {"type": "enum", "choices": ["f", "c"], "scope": "global",
                   "apply": "restart", "category": "Display",
                   "label": "Temperature scale",
                   "help": "All temperature settings are interpreted in this scale. Requires restart and page reload."},
    "time_scale_slope": {"type": "enum", "choices": ["s", "m", "h"], "scope": "global",
                         "apply": "restart", "category": "Display",
                         "label": "Rate time unit",
                         "help": "Time unit for displayed heating rates."},
    "time_scale_profile": {"type": "enum", "choices": ["s", "m", "h"], "scope": "global",
                           "apply": "restart", "category": "Display",
                           "label": "Firing profile time unit",
                           "help": "Time unit for entering and viewing firing profile targets."},
    "graph_cutoff_temp": {"type": "int", "min": 0, "max": 2000, "scope": "global",
                          "apply": "live", "category": "Display",
                          "label": "Graph cutoff temperature", "unit": "temp",
                          "help": "Stop updating the graph once the kiln cools below this after a firing."},
    "cooling_ambient_temp": {"type": "int", "min": 0, "max": 150, "scope": "global",
                             "apply": "live", "category": "Cooling",
                             "label": "Ambient temperature", "unit": "temp",
                             "help": "Room temperature assumed for cooling estimates."},
    "cooling_target_temp": {"type": "int", "min": 0, "max": 500, "scope": "global",
                            "apply": "live", "category": "Cooling",
                            "label": "Safe-to-open temperature", "unit": "temp",
                            "help": "The cooling estimate counts down to this temperature."},
    "cooling_min_samples": {"type": "int", "min": 1, "max": 1000, "scope": "global",
                            "apply": "live", "category": "Cooling",
                            "label": "Minimum cooling samples",
                            "help": "Temperature samples required before showing a cooling estimate."},
    "stall_detect_time": {"type": "int", "min": 60, "max": 86400, "scope": "global",
                          "apply": "live", "category": "Safety",
                          "label": "Stall detection time", "unit": "s", "safety": True,
                          "help": "Abort if the heater runs above 95% for this long without the temperature rising."},
    "stall_min_temp_rise": {"type": "int", "min": 1, "max": 100, "scope": "global",
                            "apply": "live", "category": "Safety",
                            "label": "Stall minimum rise", "unit": "temp", "safety": True,
                            "help": "Minimum rise expected within the stall detection time."},
    "runaway_detect_time": {"type": "int", "min": 30, "max": 86400, "scope": "global",
                            "apply": "live", "category": "Safety",
                            "label": "Runaway detection time", "unit": "s", "safety": True,
                            "help": "Emergency stop if the heater is commanded off this long while the temperature keeps rising."},
    "runaway_min_temp_rise": {"type": "int", "min": 1, "max": 200, "scope": "global",
                              "apply": "live", "category": "Safety",
                              "label": "Runaway minimum rise", "unit": "temp", "safety": True,
                              "help": "Rise (with the heater off) that triggers the emergency stop."},
    "state_save_interval": {"type": "int", "min": 5, "max": 3600, "scope": "global",
                            "apply": "live", "category": "Advanced",
                            "label": "State save interval", "unit": "s",
                            "help": "Minimum seconds between state.json writes (SD card wear protection)."},
    "automatic_restarts": {"type": "bool", "scope": "global", "apply": "live",
                           "category": "Advanced", "label": "Automatic restarts",
                           "help": "Resume the firing automatically after a power outage."},
    "automatic_restart_window": {"type": "int", "min": 1, "max": 120, "scope": "global",
                                 "apply": "live", "category": "Advanced",
                                 "label": "Automatic restart window", "unit": "min",
                                 "help": "Maximum outage duration that still auto-resumes."},
    "sensor_time_wait": {"type": "int", "min": 1, "max": 60, "scope": "global",
                         "apply": "restart", "category": "Advanced",
                         "label": "Duty cycle", "unit": "s",
                         "help": "Seconds between relay on/off decisions."},
    "temperature_average_samples": {"type": "int", "min": 1, "max": 100, "scope": "global",
                                    "apply": "restart", "category": "Advanced",
                                    "label": "Temperature samples",
                                    "help": "Thermocouple readings per duty cycle (the median is used)."},
    "ac_freq_50hz": {"type": "bool", "scope": "global", "apply": "restart",
                     "category": "Advanced", "label": "50 Hz mains filtering",
                     "help": "Enable if your mains electricity is 50 Hz."},
    "allow_legacy_profiles": {"type": "bool", "scope": "global", "apply": "live",
                              "category": "Advanced", "label": "Allow legacy firing profiles",
                              "help": "Auto-convert v1 firing profiles on load."},
    "mqtt_enabled": {"type": "bool", "scope": "global", "apply": "restart",
                     "category": "MQTT", "label": "MQTT enabled",
                     "help": "Publish kiln status and accept stop/pause/resume over MQTT."},
    "mqtt_host": {"type": "str", "max_length": 253, "scope": "global", "apply": "restart",
                  "category": "MQTT", "label": "Broker host",
                  "help": "MQTT broker hostname or IP."},
    "mqtt_port": {"type": "int", "min": 1, "max": 65535, "scope": "global", "apply": "restart",
                  "category": "MQTT", "label": "Broker port",
                  "help": "MQTT broker port."},
    "mqtt_topic_prefix": {"type": "str", "max_length": 64, "scope": "global", "apply": "restart",
                          "category": "MQTT", "label": "Topic prefix",
                          "help": "Prefix for all published topics."},
    "mqtt_publish_interval": {"type": "int", "min": 1, "max": 3600, "scope": "global",
                              "apply": "restart", "category": "MQTT",
                              "label": "Publish interval", "unit": "s",
                              "help": "Seconds between MQTT publishes."},
    "mqtt_username": {"type": "str", "max_length": 64, "nullable": True, "scope": "global",
                      "apply": "restart", "category": "MQTT", "label": "Username",
                      "help": "Leave empty for an anonymous connection."},
    "mqtt_password": {"type": "str", "max_length": 128, "nullable": True, "secret": True,
                      "scope": "global", "apply": "restart", "category": "MQTT",
                      "label": "Password",
                      "help": "Stored in plain text in storage/settings/global.json (same trust model as config.py)."},

    # ------------------------------------------------- simulation only
    "sim_initial_temp": {"type": "float", "min": -50.0, "max": 2500.0, "scope": "global",
                         "apply": "restart", "category": "Simulation", "sim_only": True,
                         "label": "Initial temperature", "unit": "temp",
                         "help": "Sensor temperature when the simulation starts."},
    "sim_t_env": {"type": "float", "min": -50.0, "max": 2500.0, "scope": "global",
                  "apply": "restart", "category": "Simulation", "sim_only": True,
                  "label": "Ambient temperature", "unit": "temp",
                  "help": "Environment temperature for heat-loss calculations."},
    "sim_c_heat": {"type": "float", "min": 1.0, "max": 1000000.0, "scope": "global",
                   "apply": "restart", "category": "Simulation", "sim_only": True,
                   "label": "Element heat capacity", "unit": "J/K",
                   "help": "Heat capacity of the heating element."},
    "sim_c_oven": {"type": "float", "min": 1.0, "max": 1000000.0, "scope": "global",
                   "apply": "restart", "category": "Simulation", "sim_only": True,
                   "label": "Oven heat capacity", "unit": "J/K",
                   "help": "Heat capacity of the oven."},
    "sim_p_heat": {"type": "float", "min": 1.0, "max": 1000000.0, "scope": "global",
                   "apply": "restart", "category": "Simulation", "sim_only": True,
                   "label": "Heating power", "unit": "W",
                   "help": "Simulated element power."},
    "sim_R_o_nocool": {"type": "float", "min": 0.001, "max": 100.0, "scope": "global",
                       "apply": "restart", "category": "Simulation", "sim_only": True,
                       "label": "Oven-to-environment resistance", "unit": "K/W",
                       "help": "Higher = better insulation, slower cooling."},
    "sim_R_o_cool": {"type": "float", "min": 0.001, "max": 100.0, "scope": "global",
                     "apply": "restart", "category": "Simulation", "sim_only": True,
                     "label": "Oven-to-environment resistance (cooling)", "unit": "K/W",
                     "help": "Thermal resistance with cooling."},
    "sim_R_ho_noair": {"type": "float", "min": 0.001, "max": 100.0, "scope": "global",
                       "apply": "restart", "category": "Simulation", "sim_only": True,
                       "label": "Element-to-oven resistance", "unit": "K/W",
                       "help": "Thermal resistance from the element to the oven."},
    "sim_R_ho_air": {"type": "float", "min": 0.001, "max": 100.0, "scope": "global",
                     "apply": "restart", "category": "Simulation", "sim_only": True,
                     "label": "Element-to-oven resistance (air)", "unit": "K/W",
                     "help": "Thermal resistance with internal air circulation."},
    "sim_speedup_factor": {"type": "int", "min": 1, "max": 10000, "scope": "global",
                           "apply": "restart", "category": "Simulation", "sim_only": True,
                           "label": "Speedup factor",
                           "help": "Run simulations N times faster than real time."},
}

# The 12 thermocouple-error ignore flags share shape; generate them.
# mid_firing_editable is deliberate: their documented purpose is mid-firing
# triage ("ignore this error to complete a firing") — see spec section 6.
_IGNORE_FLAG_LABELS = {
    "ignore_temp_too_high": "temperature above emergency shutoff",
    "ignore_tc_lost_connection": "thermocouple lost connection",
    "ignore_tc_cold_junction_range_error": "cold junction range error",
    "ignore_tc_range_error": "thermocouple range error",
    "ignore_tc_cold_junction_temp_high": "cold junction temperature high",
    "ignore_tc_cold_junction_temp_low": "cold junction temperature low",
    "ignore_tc_temp_high": "thermocouple temperature high",
    "ignore_tc_temp_low": "thermocouple temperature low",
    "ignore_tc_voltage_error": "thermocouple voltage error",
    "ignore_tc_short_errors": "brief thermocouple error bursts",
    "ignore_tc_unknown_error": "unknown thermocouple error",
    "ignore_tc_too_many_errors": "ALL thermocouple errors (master override)",
}
for _key, _desc in _IGNORE_FLAG_LABELS.items():
    SETTINGS_SCHEMA[_key] = {
        "type": "bool", "scope": "global", "apply": "live",
        "category": "Safety",
        "label": "Ignore: %s" % _desc,
        "help": "Log and keep firing when this error occurs. Enable only for mid-firing triage you understand.",
        "safety": True, "mid_firing_editable": True,
    }
